In [2]:
import pandas as pd

In [3]:
cbsl = pd.read_csv(r"C:\USD-LKR Forecasting\data\raw\cbsl.csv")

In [4]:
cbsl.head()

         date base quote        type     value
0  2010-05-07  AED   LKR  indicative   30.9558
1  2010-05-07  AUD   LKR  indicative  101.1737
2  2010-05-07  BDT   LKR  indicative    1.6460
3  2010-05-07  BHD   LKR  indicative  301.6249
4  2010-05-07  BND   LKR  indicative   81.7791

In [5]:
cbsl.shape

(190935, 5)

In [6]:
cbsl.columns

Index(['date', 'base', 'quote', 'type', 'value'], dtype='str')

In [7]:
cbsl["type"].unique()

<StringArray>
['indicative']
Length: 1, dtype: str

In [8]:
cbsl.head()

         date base quote        type     value
0  2010-05-07  AED   LKR  indicative   30.9558
1  2010-05-07  AUD   LKR  indicative  101.1737
2  2010-05-07  BDT   LKR  indicative    1.6460
3  2010-05-07  BHD   LKR  indicative  301.6249
4  2010-05-07  BND   LKR  indicative   81.7791

In [9]:
usd_lkr = cbsl[
    (cbsl["base"] == "USD") &
    (cbsl["quote"] == "LKR") &
    (cbsl["type"] == "indicative")
].copy()

In [10]:
usd_lkr.shape

(3499, 5)

In [11]:
usd_lkr = (
    usd_lkr[["date", "value"]]
    .rename(columns={"value": "USD_LKR"})
)

In [12]:
usd_lkr.head()

           date   USD_LKR
47   2010-05-07  113.6975
98   2010-05-11  113.6292
149  2010-05-12  113.6854
200  2010-05-13  113.7009
251  2010-05-14  113.6573

In [13]:
usd_lkr["date"] = pd.to_datetime(usd_lkr["date"])

In [14]:
usd_lkr = usd_lkr.sort_values("date")

In [15]:
usd_lkr = usd_lkr.drop_duplicates("date")

In [16]:
usd_lkr = usd_lkr.set_index("date")

In [17]:
usd_lkr.head()

             USD_LKR
date
2010-05-07  113.6975
2010-05-11  113.6292
2010-05-12  113.6854
2010-05-13  113.7009
2010-05-14  113.6573

In [18]:
usd_lkr.isna().sum()

USD_LKR    0
dtype: int64

In [19]:
usd_lkr.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 3499 entries, 2010-05-07 to 2026-09-25
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   USD_LKR  3499 non-null   float64
dtypes: float64(1)
memory usage: 54.7 KB

In [20]:
usd_lkr.index.min()

Timestamp('2010-05-07 00:00:00')

In [23]:
usd_lkr.to_csv("../data/processed/master_dataset.csv")